### ISSUE TITLE
Change go module name to "github.com/eater-altria/protoc-gen-http-ts"?

### ISSUE THREAD

**Issue by kvii** [eater-altria/protoc-gen-http-ts#4]
So that I can install it with `go install github.com/eater-altria/protoc-gen-http-ts@latest`。

**Comment by eater-altria** [comment]
sure, I will do this today night!

**Comment by eater-altria** [comment]
https://pkg.go.dev/github.com/eater-altria/protoc-gen-http-ts

It's here
